// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssgtxtexwhwttbcqccgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZ3R4dGV4d2h3dHRiY3FjY2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NzA1NzUsImV4cCI6MjA1MzA0NjU3NX0.i6m4Zz-Pc9DSCvEIGrkJy_Dbz9LwK02m-ZT5DvjsVcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);